// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnoSkillingAPI.Data;

#nullable disable

namespace TechnoSkillingAPI.Migrations
{
    [DbContext(typeof(TechnoSkillingDbContext))]
    [Migration("20250204082857_Add_BlogPost_UserInfoRelationCreate")]
    partial class Add_BlogPost_UserInfoRelationCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnoSkillingAPI.Data.BlogCategory", b =>
                {
                    b.Property<Guid>("BlogCatgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlogCatgDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("BlogCatgIconPic")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlogCatgName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("int");

                    b.HasKey("BlogCatgId");

                    b.HasIndex("BlogCatgName")
                        .IsUnique();

                    b.ToTable("BlogCategories");
                });

            modelBuilder.Entity("TechnoSkillingAPI.Data.BlogPost", b =>
                {
                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogCatgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlogPosText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogPostItemPic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BlogPostPostedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BlogPostPostedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BlogPostStatus")
                        .HasColumnType("int");

                    b.Property<string>("BlogPostTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ParentCategoryBlogCatgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BlogPostId");

                    b.HasIndex("ParentCategoryBlogCatgId");

                    b.HasIndex("PostedUserId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("TechnoSkillingAPI.Data.RoleMaster", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("RoleMasters");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("939794a9-f9c3-498b-9937-26da1470c89c"),
                            RoleName = "Admin",
                            Status = 1
                        },
                        new
                        {
                            RoleId = new Guid("b73d97bc-8fc7-4c33-a8ea-f0756eca0a2a"),
                            RoleName = "Guest",
                            Status = 1
                        });
                });

            modelBuilder.Entity("TechnoSkillingAPI.Data.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentRoleRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ParentRoleRoleId");

                    b.ToTable("UserInfos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab8f8762-2e38-4722-a53b-5b104880377c"),
                            DisplayName = "Sai Durga",
                            Email = "sai_prasad_veluri@yahoo.com",
                            Password = "3B58A+FiOXs1W28ciV3983kNmMELkgxV6RJyuO7K2io=",
                            RoleId = new Guid("939794a9-f9c3-498b-9937-26da1470c89c")
                        });
                });

            modelBuilder.Entity("TechnoSkillingAPI.Data.BlogPost", b =>
                {
                    b.HasOne("TechnoSkillingAPI.Data.BlogCategory", "ParentCategory")
                        .WithMany("ChildPosts")
                        .HasForeignKey("ParentCategoryBlogCatgId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TechnoSkillingAPI.Data.UserInfo", "PostedUser")
                        .WithMany("UserPosts")
                        .HasForeignKey("PostedUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentCategory");

                    b.Navigation("PostedUser");
                });

            modelBuilder.Entity("TechnoSkillingAPI.Data.UserInfo", b =>
                {
                    b.HasOne("TechnoSkillingAPI.Data.RoleMaster", "ParentRole")
                        .WithMany("UsersInRole")
                        .HasForeignKey("ParentRoleRoleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentRole");
                });

            modelBuilder.Entity("TechnoSkillingAPI.Data.BlogCategory", b =>
                {
                    b.Navigation("ChildPosts");
                });

            modelBuilder.Entity("TechnoSkillingAPI.Data.RoleMaster", b =>
                {
                    b.Navigation("UsersInRole");
                });

            modelBuilder.Entity("TechnoSkillingAPI.Data.UserInfo", b =>
                {
                    b.Navigation("UserPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
