// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnoSkillingAPI.Data;

#nullable disable

namespace TechnoSkillingAPI.Migrations
{
    [DbContext(typeof(TechnoSkillingDbContext))]
    partial class TechnoSkillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnoSkillingAPI.Data.RoleMaster", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("RoleMasters");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("939794a9-f9c3-498b-9937-26da1470c89c"),
                            RoleName = "Admin",
                            Status = 1
                        },
                        new
                        {
                            RoleId = new Guid("b73d97bc-8fc7-4c33-a8ea-f0756eca0a2a"),
                            RoleName = "Guest",
                            Status = 1
                        });
                });

            modelBuilder.Entity("TechnoSkillingAPI.Data.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentRoleRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ParentRoleRoleId");

                    b.ToTable("UserInfos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab8f8762-2e38-4722-a53b-5b104880377c"),
                            DisplayName = "Sai Durga",
                            Email = "sai_prasad_veluri@yahoo.com",
                            Password = "3B58A+FiOXs1W28ciV3983kNmMELkgxV6RJyuO7K2io=",
                            RoleId = new Guid("939794a9-f9c3-498b-9937-26da1470c89c")
                        });
                });

            modelBuilder.Entity("TechnoSkillingAPI.Data.UserInfo", b =>
                {
                    b.HasOne("TechnoSkillingAPI.Data.RoleMaster", "ParentRole")
                        .WithMany("UsersInRole")
                        .HasForeignKey("ParentRoleRoleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentRole");
                });

            modelBuilder.Entity("TechnoSkillingAPI.Data.RoleMaster", b =>
                {
                    b.Navigation("UsersInRole");
                });
#pragma warning restore 612, 618
        }
    }
}
